spring:
  application:
    name: paygate
  profiles:
    default: dev
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: false
  config:
    import: classpath:/settings/vn_pay.yml