spring:
  application:
    name: interview_practice
  profiles:
    default: dev
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  config:
    import:
      - classpath:cache-settings.yml