spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test_interview_practice
    username: postgres
    password: 123456
    pool:
      max-size: 20
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: interview_practice
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
#      max-poll-records: 1000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        reconnect:
          backoff:
            ms: 10000
            max:
              ms: 10000
    listener:
      concurrency: 3
  elasticsearch:
    uris: http://localhost:9200
logging:
  level:
    io:
      r2dbc:
        postgresql:
          QUERY: DEBUG
          PARAM: DEBUG
    org:
      elasticsearch:
        client: DEBUG
      apache:
        http.wire: INFO
